"""empty message

Revision ID: 711c14fbda99
Revises: 
Create Date: 2022-06-18 21:04:45.593230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711c14fbda99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
